"""Dynamic Squid configuration generation."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ..const import (
    CONTAINER_CERT_DIR,
    CONTAINER_CONFIG_DIR,
    CONTAINER_LOG_DIR,
    CONTAINER_PASSWD_FILE,
)
from ..security.security_utils import secure_file_write

_LOGGER = logging.getLogger(__name__)


class SquidConfigGenerator:
    """Generates Squid configuration files."""

    def __init__(self, instance_name: str, port: int, https_enabled: bool = False) -> None:
        """Initialize config generator.

        Args:
            instance_name: Name of the proxy instance
            port: Port number for the proxy
            https_enabled: Whether HTTPS is enabled
        """
        self.instance_name = instance_name
        self.port = port
        self.https_enabled = https_enabled

    def generate_config(self, config_file: Path) -> None:
        """Generate Squid configuration file.

        Args:
            config_file: Path to write the configuration file
        """
        config_lines = [
            "# Squid configuration for %s" % self.instance_name,
            "# Generated by Squid Proxy Manager",
            "",
            "# Basic settings",
            "http_port %d" % self.port,
            "",
            "# Access control",
            "acl localnet src 10.0.0.0/8",
            "acl localnet src 172.16.0.0/12",
            "acl localnet src 192.168.0.0/16",
            "acl localnet src fc00::/7",
            "acl localnet src fe80::/10",
            "",
            "# Authentication",
            "auth_param basic program /usr/lib/squid/basic_ncsa_auth %s" % CONTAINER_PASSWD_FILE,
            "auth_param basic children 5",
            "auth_param basic realm Squid Proxy",
            "auth_param basic credentialsttl 2 hours",
            "",
            "# ACL for authenticated users",
            "acl authenticated proxy_auth REQUIRED",
            "",
            "# HTTP access",
            "http_access allow authenticated",
            "http_access deny all",
            "",
            "# HTTPS/SSL configuration",
        ]

        if self.https_enabled:
            cert_file = f"{CONTAINER_CERT_DIR}/proxyCA.pem"
            config_lines.extend(
                [
                    "https_port %d cert=%s" % (self.port, cert_file),
                    "ssl_bump server-first all",
                    "sslcrtd_program /usr/lib/squid/security_file_certgen -s %s/ssl_db -M 4MB"
                    % CONTAINER_CERT_DIR,
                    "",
                ]
            )

        config_lines.extend(
            [
                "# Logging",
                "access_log %s/access.log squid" % CONTAINER_LOG_DIR,
                "cache_log %s/cache.log" % CONTAINER_LOG_DIR,
                "",
                "# Cache settings (minimal for proxy-only mode)",
                "cache_dir ufs %s/cache 100 16 256" % CONTAINER_LOG_DIR,
                "cache_mem 64 MB",
                "maximum_object_size_in_memory 512 KB",
                "",
                "# Security hardening",
                "via off",
                "forwarded_for delete",
                "request_header_access X-Forwarded-For deny all",
                "request_header_access Via deny all",
                "request_header_access Cache-Control deny all",
                "",
                "# Disable unnecessary features",
                "cache deny all",
                "",
                "# Error pages",
                "error_directory /usr/share/squid/errors/en",
                "",
            ]
        )

        config_content = "\n".join(config_lines)
        secure_file_write(config_file, config_content)

        _LOGGER.info("Generated Squid configuration for %s on port %d", self.instance_name, self.port)
