"""Dynamic Squid configuration generation."""

import grp
import logging
import os
import pwd
import shlex
from pathlib import Path

_LOGGER = logging.getLogger(__name__)

# Default container paths (can be overridden for testing)
DEFAULT_DATA_DIR = "/data/squid_proxy_manager"


class SquidConfigGenerator:
    """Generates Squid configuration files."""

    def __init__(
        self,
        instance_name: str,
        port: int,
        https_enabled: bool = False,
        data_dir: str = DEFAULT_DATA_DIR,
    ) -> None:
        """Initialize config generator.

        Args:
            instance_name: Name of the proxy instance
            port: Port number for the proxy
            https_enabled: Whether HTTPS is enabled
            data_dir: Base data directory for all instance data
        """
        self.instance_name = instance_name
        self.port = port
        self.https_enabled = https_enabled
        self.data_dir = data_dir

    def generate_config(self, config_file: Path) -> None:
        """Generate Squid configuration file.

        Args:
            config_file: Path to write the configuration file
        """
        # Calculate instance-specific paths using configurable data_dir
        instance_log_dir = f"{self.data_dir}/logs/{self.instance_name}"
        instance_cert_dir = f"{self.data_dir}/certs/{self.instance_name}"
        instance_data_dir = f"{self.data_dir}/{self.instance_name}"

        config_lines = [
            f"# Squid configuration for {self.instance_name}",
            "# Generated by Squid Proxy Manager Add-on",
            "",
            "# Basic settings",
            "pid_filename none",  # Prevent PID file conflicts
        ]

        # Ensure Squid runs as a non-root user to match file ownership/permissions
        try:
            if os.getuid() == 0:
                chosen_user = None
                for candidate in ("proxy", "squid", "nobody"):
                    try:
                        pwd.getpwnam(candidate)
                        chosen_user = candidate
                        break
                    except KeyError:
                        continue
                if chosen_user:
                    chosen_group = grp.getgrgid(pwd.getpwnam(chosen_user).pw_gid).gr_name
                else:
                    chosen_user = pwd.getpwuid(os.getuid()).pw_name
                    chosen_group = grp.getgrgid(os.getgid()).gr_name
            else:
                chosen_user = pwd.getpwuid(os.getuid()).pw_name
                chosen_group = grp.getgrgid(os.getgid()).gr_name
            config_lines.extend(
                [
                    f"cache_effective_user {chosen_user}",
                    f"cache_effective_group {chosen_group}",
                    "",
                ]
            )
        except KeyError:
            _LOGGER.warning("Unable to resolve effective user/group for squid config")

        # If HTTPS is enabled, we use https_port instead of http_port on that port
        if self.https_enabled:
            cert_file = f"{instance_cert_dir}/squid.crt"
            key_file = f"{instance_cert_dir}/squid.key"
            # For Squid 5.9 native HTTPS proxy, we use tls-cert and tls-key
            # Do NOT include ssl_bump - it requires signing certificates for dynamic cert generation
            # We just want clients to connect to the proxy via HTTPS (encrypted proxy connection)
            https_line = f"https_port {self.port} tls-cert={cert_file} tls-key={key_file}"
            config_lines.append(https_line)
            _LOGGER.info("HTTPS config: %s", https_line)
            _LOGGER.info("Certificate path: %s", cert_file)
            _LOGGER.info("Key path: %s", key_file)
        else:
            config_lines.append(f"http_port {self.port}")

        config_lines.extend(
            [
                "",
                "# Access control",
                "acl localnet src 10.0.0.0/8",
                "acl localnet src 172.16.0.0/12",
                "acl localnet src 192.168.0.0/16",
                "acl localnet src fc00::/7",
                "acl localnet src fe80::/10",
                "",
                "# Authentication",
                f"auth_param basic program /usr/lib/squid/basic_ncsa_auth {instance_data_dir}/passwd",
                "auth_param basic children 5",
                f"auth_param basic realm {shlex.quote('Squid Proxy')}",
                "auth_param basic credentialsttl 2 hours",
                "",
                "# ACL for authenticated users",
                "acl authenticated proxy_auth REQUIRED",
                "",
                "# HTTP access",
                "http_access allow authenticated",
                "http_access deny all",
                "",
                "# Logging",
                # Use stdio module for logging as recommended by Squid 5.9
                f"access_log stdio:{instance_log_dir}/access.log squid",
                f"cache_log {instance_log_dir}/cache.log",
                "",
                "# Cache settings (minimal for proxy-only mode)",
                f"cache_dir ufs {instance_log_dir}/cache 100 16 256",
                "cache_mem 64 MB",
                "maximum_object_size_in_memory 512 KB",
                "",
                "# Security hardening",
                "via off",
                "forwarded_for delete",
                "request_header_access X-Forwarded-For deny all",
                "request_header_access Via deny all",
                "request_header_access Cache-Control deny all",
                "",
                "# Disable unnecessary features",
                "cache deny all",
                "",
            ]
        )

        config_lines.extend(
            [
                "# Error pages",
                "error_directory /usr/share/squid/errors/en",
                "",
            ]
        )

        config_content = "\n".join(config_lines)
        config_file.write_text(config_content, encoding="utf-8")
        config_file.chmod(0o640)

        _LOGGER.info(
            "Generated Squid configuration for %s on port %d", self.instance_name, self.port
        )
