"""Dynamic Squid configuration generation."""
import logging
from pathlib import Path

_LOGGER = logging.getLogger(__name__)

# Container paths
CONTAINER_CERT_DIR = "/etc/squid/ssl_cert"
CONTAINER_CONFIG_DIR = "/etc/squid"
CONTAINER_LOG_DIR = "/var/log/squid"
CONTAINER_PASSWD_FILE = "/etc/squid/passwd"


class SquidConfigGenerator:
    """Generates Squid configuration files."""

    def __init__(self, instance_name: str, port: int, https_enabled: bool = False) -> None:
        """Initialize config generator.

        Args:
            instance_name: Name of the proxy instance
            port: Port number for the proxy
            https_enabled: Whether HTTPS is enabled
        """
        self.instance_name = instance_name
        self.port = port
        self.https_enabled = https_enabled

    def generate_config(self, config_file: Path) -> None:
        """Generate Squid configuration file.

        Args:
            config_file: Path to write the configuration file
        """
        config_lines = [
            f"# Squid configuration for {self.instance_name}",
            "# Generated by Squid Proxy Manager Add-on",
            "",
            "# Basic settings",
            f"http_port {self.port}",
            "",
            "# Access control",
            "acl localnet src 10.0.0.0/8",
            "acl localnet src 172.16.0.0/12",
            "acl localnet src 192.168.0.0/16",
            "acl localnet src fc00::/7",
            "acl localnet src fe80::/10",
            "",
            "# Authentication",
            f"auth_param basic program /usr/lib/squid/basic_ncsa_auth {CONTAINER_PASSWD_FILE}",
            "auth_param basic children 5",
            "auth_param basic realm Squid Proxy",
            "auth_param basic credentialsttl 2 hours",
            "",
            "# ACL for authenticated users",
            "acl authenticated proxy_auth REQUIRED",
            "",
            "# HTTP access",
            "http_access allow authenticated",
            "http_access deny all",
            "",
            "# HTTPS/SSL configuration",
        ]

        if self.https_enabled:
            cert_file = f"{CONTAINER_CERT_DIR}/proxyCA.pem"
            config_lines.extend(
                [
                    f"https_port {self.port} cert={cert_file}",
                    "ssl_bump server-first all",
                    f"sslcrtd_program /usr/lib/squid/security_file_certgen -s {CONTAINER_CERT_DIR}/ssl_db -M 4MB",
                    "",
                ]
            )

        config_lines.extend(
            [
                "# Logging",
                f"access_log {CONTAINER_LOG_DIR}/access.log squid",
                f"cache_log {CONTAINER_LOG_DIR}/cache.log",
                "",
                "# Cache settings (minimal for proxy-only mode)",
                f"cache_dir ufs {CONTAINER_LOG_DIR}/cache 100 16 256",
                "cache_mem 64 MB",
                "maximum_object_size_in_memory 512 KB",
                "",
                "# Security hardening",
                "via off",
                "forwarded_for delete",
                "request_header_access X-Forwarded-For deny all",
                "request_header_access Via deny all",
                "request_header_access Cache-Control deny all",
                "",
                "# Disable unnecessary features",
                "cache deny all",
                "",
                "# Error pages",
                "error_directory /usr/share/squid/errors/en",
                "",
            ]
        )

        config_content = "\n".join(config_lines)
        config_file.write_text(config_content, encoding="utf-8")
        config_file.chmod(0o644)

        _LOGGER.info("Generated Squid configuration for %s on port %d", self.instance_name, self.port)
