"""Dynamic Squid configuration generation."""
import logging
from pathlib import Path

_LOGGER = logging.getLogger(__name__)

# Container paths
CONTAINER_CERT_DIR = "/etc/squid/ssl_cert"
CONTAINER_CONFIG_DIR = "/etc/squid"
CONTAINER_LOG_DIR = "/data/squid_proxy_manager/logs"
CONTAINER_PASSWD_FILE = "/etc/squid/passwd"


class SquidConfigGenerator:
    """Generates Squid configuration files."""

    def __init__(self, instance_name: str, port: int, https_enabled: bool = False) -> None:
        """Initialize config generator.

        Args:
            instance_name: Name of the proxy instance
            port: Port number for the proxy
            https_enabled: Whether HTTPS is enabled
        """
        self.instance_name = instance_name
        self.port = port
        self.https_enabled = https_enabled

    def generate_config(self, config_file: Path) -> None:
        """Generate Squid configuration file.

        Args:
            config_file: Path to write the configuration file
        """
        # Calculate instance-specific paths
        instance_log_dir = f"{CONTAINER_LOG_DIR}/{self.instance_name}"
        instance_cert_dir = f"{CONTAINER_CERT_DIR}/{self.instance_name}"
        instance_data_dir = f"/data/squid_proxy_manager/{self.instance_name}"

        config_lines = [
            f"# Squid configuration for {self.instance_name}",
            "# Generated by Squid Proxy Manager Add-on",
            "",
            "# Basic settings",
            "pid_filename none",  # Prevent PID file conflicts
        ]

        # If HTTPS is enabled, we use https_port instead of http_port on that port
        if self.https_enabled:
            cert_file = f"{instance_cert_dir}/squid.crt"
            key_file = f"{instance_cert_dir}/squid.key"
            # Some Squid versions are picky about quotes, but for these it's usually okay
            # We'll use them only if necessary.
            config_lines.append(
                f'https_port {self.port} cert="{cert_file}" key="{key_file}" generate-host-certificates=on dynamic_cert_mem_cache_size=4MB'
            )
            config_lines.append("ssl_bump server-first all")
            config_lines.append(
                f"sslcrtd_program /usr/lib/squid/security_file_certgen -s {instance_cert_dir}/ssl_db -M 4MB"
            )
        else:
            config_lines.append(f"http_port {self.port}")

        config_lines.extend(
            [
                "",
                "# Access control",
                "acl localnet src 10.0.0.0/8",
                "acl localnet src 172.16.0.0/12",
                "acl localnet src 192.168.0.0/16",
                "acl localnet src fc00::/7",
                "acl localnet src fe80::/10",
                "",
                "# Authentication",
                f"auth_param basic program /usr/lib/squid/basic_ncsa_auth {instance_data_dir}/passwd",
                "auth_param basic children 5",
                "auth_param basic realm Squid Proxy",
                "auth_param basic credentialsttl 2 hours",
                "",
                "# ACL for authenticated users",
                "acl authenticated proxy_auth REQUIRED",
                "",
                "# HTTP access",
                "http_access allow authenticated",
                "http_access deny all",
                "",
                "# Logging",
                # Use stdio module for logging as recommended by Squid 5.9
                f"access_log stdio:{instance_log_dir}/access.log squid",
                f"cache_log {instance_log_dir}/cache.log",
                "",
                "# Cache settings (minimal for proxy-only mode)",
                f"cache_dir ufs {instance_log_dir}/cache 100 16 256",
                "cache_mem 64 MB",
                "maximum_object_size_in_memory 512 KB",
                "",
                "# Security hardening",
                "via off",
                "forwarded_for delete",
                "request_header_access X-Forwarded-For deny all",
                "request_header_access Via deny all",
                "request_header_access Cache-Control deny all",
                "",
                "# Disable unnecessary features",
                "cache deny all",
                "",
                "# Error pages",
                "error_directory /usr/share/squid/errors/en",
                "",
            ]
        )

        config_content = "\n".join(config_lines)
        config_file.write_text(config_content, encoding="utf-8")
        config_file.chmod(0o644)

        _LOGGER.info(
            "Generated Squid configuration for %s on port %d", self.instance_name, self.port
        )
